/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppUsoMensualRouteImport } from './routes/_app.uso-mensual'
import { Route as AppNotificacionesRouteImport } from './routes/_app.notificaciones'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConversacionesRouteImport } from './routes/_app.conversaciones'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppAssistiaRouteImport } from './routes/_app.assistia'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUsoMensualRoute = AppUsoMensualRouteImport.update({
  id: '/uso-mensual',
  path: '/uso-mensual',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesRoute = AppNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConversacionesRoute = AppConversacionesRouteImport.update({
  id: '/conversaciones',
  path: '/conversaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistiaRoute = AppAssistiaRouteImport.update({
  id: '/assistia',
  path: '/assistia',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/assistia': typeof AppAssistiaRoute
  '/billing': typeof AppBillingRoute
  '/clientes': typeof AppClientesRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/conversaciones': typeof AppConversacionesRoute
  '/dashboard': typeof AppDashboardRoute
  '/notificaciones': typeof AppNotificacionesRoute
  '/uso-mensual': typeof AppUsoMensualRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/assistia': typeof AppAssistiaRoute
  '/billing': typeof AppBillingRoute
  '/clientes': typeof AppClientesRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/conversaciones': typeof AppConversacionesRoute
  '/dashboard': typeof AppDashboardRoute
  '/notificaciones': typeof AppNotificacionesRoute
  '/uso-mensual': typeof AppUsoMensualRoute
  '/whatsapp': typeof AppWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/assistia': typeof AppAssistiaRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/conversaciones': typeof AppConversacionesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notificaciones': typeof AppNotificacionesRoute
  '/_app/uso-mensual': typeof AppUsoMensualRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/assistia'
    | '/billing'
    | '/clientes'
    | '/configuracion'
    | '/conversaciones'
    | '/dashboard'
    | '/notificaciones'
    | '/uso-mensual'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/assistia'
    | '/billing'
    | '/clientes'
    | '/configuracion'
    | '/conversaciones'
    | '/dashboard'
    | '/notificaciones'
    | '/uso-mensual'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/assistia'
    | '/_app/billing'
    | '/_app/clientes'
    | '/_app/configuracion'
    | '/_app/conversaciones'
    | '/_app/dashboard'
    | '/_app/notificaciones'
    | '/_app/uso-mensual'
    | '/_app/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uso-mensual': {
      id: '/_app/uso-mensual'
      path: '/uso-mensual'
      fullPath: '/uso-mensual'
      preLoaderRoute: typeof AppUsoMensualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones': {
      id: '/_app/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AppNotificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversaciones': {
      id: '/_app/conversaciones'
      path: '/conversaciones'
      fullPath: '/conversaciones'
      preLoaderRoute: typeof AppConversacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistia': {
      id: '/_app/assistia'
      path: '/assistia'
      fullPath: '/assistia'
      preLoaderRoute: typeof AppAssistiaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistiaRoute: typeof AppAssistiaRoute
  AppBillingRoute: typeof AppBillingRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppConversacionesRoute: typeof AppConversacionesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificacionesRoute: typeof AppNotificacionesRoute
  AppUsoMensualRoute: typeof AppUsoMensualRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistiaRoute: AppAssistiaRoute,
  AppBillingRoute: AppBillingRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppConversacionesRoute: AppConversacionesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificacionesRoute: AppNotificacionesRoute,
  AppUsoMensualRoute: AppUsoMensualRoute,
  AppWhatsappRoute: AppWhatsappRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
